### ISSUE TITLE
Example code doesn't work on fresh install

### ISSUE THREAD

**Issue by hippyjim** [aryelds/yii2-sweet-alert#1]
When I try to use it as demonstrated, I get:

`opendir(/home/jim/PhpstormProjects/parent-portal-yii2/basic/vendor/bower/sweetalert/docs-src/assets/sweetalert): failed to open dir: No such file or directory`

In controller:

`Yii::$app->session->setFlash('success', [
        'text' => 'My custom text',
        'title' => 'My custom title',
        'type' => 'success',
        'timer' => 3000,
        'showConfirmButton' => false
    ]);`

In main layout: 

`foreach (Yii::$app->session->getAllFlashes() as $message) {
    echo SweetAlert::widget([
        'options' => [
            'title' => (!empty($message['title'])) ? Html::encode($message['title']) : 'Title Not Set!',
            'text' => (!empty($message['text'])) ? Html::encode($message['text']) : 'Text Not Set!',
            'type' => (!empty($message['type'])) ? $message['type'] : SweetAlert::TYPE_INFO,
            'timer' => (!empty($message['timer'])) ? $message['timer'] : 4000,
            'showConfirmButton' =>  (!empty($message['showConfirmButton'])) ? $message['showConfirmButton'] : true
        ]
    ]);
}`

The file it's pointing to is a broken link.

`jim@pingu:~/PhpstormProjects/parent-portal-yii2/basic$ ls -lah /home/jim/PhpstormProjects/parent-portal-yii2/basic/vendor/bower/sweetalert/docs-src/assets/

total 20K
drwxrwxr-x 5 jim jim 4.0K Dec 14 13:36 .
drwxrwxr-x 5 jim jim 4.0K Dec 14 13:36 ..
drwxrwxr-x 2 jim jim 4.0K Dec 14 13:36 css
drwxrwxr-x 2 jim jim 4.0K Dec 14 13:36 images
drwxrwxr-x 2 jim jim 4.0K Dec 14 13:36 js
lrwxrwxrwx 1 jim jim   11 Apr 27 15:30 sweetalert -> ../../dist/`

It's like it's trying to look for files that it hasn't installed. Ideas?

(apologies for formatting, I can either have newlines, or highlighting, but not both)

**Comment by aryelds** [comment]
I just fix the package
